version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: tasks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U botuser -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    environment:
      BOT_TOKEN: "7563468648:AAESbhvYtnCN3mF8aOmr-lX0axBF-U5vMoo"
      POSTGRES_HOST: db
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: tasks
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bot-network

volumes:
  postgres_data:

networks:
  bot-network:
